services:
  cubestore:
    restart: always
    image: cubejs/cubestore:non-avx
    env_file:
      - .env
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_MYSQL_PORT=0
      - CUBESTORE_MYSQL_BIND_ADDR=127.0.0.1:3307
    volumes:
      - .cubestore:/cube/data
 
  cube:
    restart: always
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - cubestore
    links:
      - cubestore
    volumes:
      - ./model:/cube/conf/model
      - .:/cube/conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    